plugins {
	id 'java'
    id 'org.springframework.boot' version '4.1.0-M2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.brycenkorea'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

ext {
    set('springAiVersion', "2.0.0-M4")
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-jackson'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
//    implementation 'com.mysql:mysql-connector-j'
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'org.postgresql:r2dbc-postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:3.0.2'

    // Now declare Jackson modules WITHOUT versions
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.opentelemetry:opentelemetry-api:1.51.0'
//	implementation 'org.liquibase:liquibase-core:4.33.0'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
	implementation 'com.slack.api:slack-api-client:1.45.3'
    // Spring AI
//    implementation 'org.springframework.ai:spring-ai-openai-spring-boot-starter'
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
    implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory'
    implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-redis'
    implementation 'org.springframework.ai:spring-ai-advisors-vector-store'
    implementation 'org.springframework.ai:spring-ai-rag'
    implementation 'org.springframework.ai:spring-ai-tika-document-reader'
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai-embedding'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'com.google.genai:google-genai:1.42.0'
    // Spring AI의 API 재시도(Retry) 기능을 위한 필수 라이브러리
    implementation 'org.springframework.ai:spring-ai-retry'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc'
    implementation 'org.springframework.ai:spring-ai-starter-mcp-client-webflux'
    implementation 'org.jobrunr:jobrunr-spring-boot-4-starter:8.5.2'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	runtimeOnly 'com.h2database:h2'
	compileOnly 'org.projectlombok:lombok:1.18.38'
	annotationProcessor 'org.projectlombok:lombok:1.18.38'

	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

	testImplementation 'io.rest-assured:rest-assured:5.5.5'
	testImplementation 'org.springframework.boot:spring-boot-starter-jackson-test'
	testImplementation 'org.mockito:mockito-core:5.2.0'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testCompileOnly 'org.projectlombok:lombok:1.18.38'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

tasks.named('test') {
	useJUnitPlatform()
}
