spring:
  application:
    name: template-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/groupware
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/groupware
    username: appuser
    password: apppass
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.xml"
    default-schema: public
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema-dev.sql
      data-locations: classpath:data-dev.sql
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
jwt:
  secret: mysecretkeymysecretkeymysecretkey12

server:
  port: 8080

crawler:
  url: http://localhost:8081

logging:
  level:
    io.r2dbc.proxy.query: DEBUG # 실행되는 모든 SQL 쿼리 로깅

    # 스레드 전환 시 발생하는 불필요한 관찰 컨텍스트 경고 차단
    io.micrometer.observation.contextpropagation: ERROR
    org:
      springframework:
        web.reactive.function.client.ExchangeFunctions: TRACE
        ai:
          chat:
            client:
              advisor=DEBUG:
    # --- [Spring/Hibernate/MyBatis] ---
    org.springframework: INFO                # Spring 내부 (DEBUG면 너무 시끄러움)
    org.springframework.web: INFO            # Web 요청/응답, HandlerMapping 등

    org.hibernate.SQL: DEBUG                 # SQL 로그 (쿼리)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 바인딩 (파라미터 추적 원할 때만 TRACE!)
    org.hibernate.type: WARN                 # (필요 시만 INFO/TRACE)

    # --- [보안] ---
    org.springframework.security: INFO       # Security 관련 로그

    # --- [Swagger/OpenAPI] ---
    org.springdoc: WARN                      # springdoc-openapi는 WARN 이상이면 됨

    # --- [JWT/보안] ---
    io.jsonwebtoken: WARN

    # --- [오픈텔레메트리/관측] ---
    io.opentelemetry: WARN

    # --- [테스트용 H2] ---
    org.h2: WARN

    # --- [노이즈 방지: JMX/RMI/Serialization] ---
    java.io.serialization: WARN
    sun.rmi: WARN
    javax.management: WARN
    java.management: WARN
    jmx: WARN

    # --- [MapStruct, Lombok, 기타] ---
    org.mapstruct: WARN
    org.projectlombok: WARN
    com.googlecode.owasp: WARN
    # --- [spring ai] ---
    org.springframework.ai: INFO
    org.springframework.ai.vectorstore: DEBUG
    org.springframework.ai.rag: DEBUG